src/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("feed", views.my_post, name="my_feed"),
]

src/litrevue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("feed/", include("feed.urls")),
    path("tickets/", include("tickets.urls")),
    path("reviews/", include("review.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/review/urls.py
from django.urls import path

from . import views

app_name = "review"
urlpatterns = [
    path("create-review/", views.create_review, name="create-review"),
    path("review/<int:ticket_id>/", views.respond_to_ticket, name="review"),
    path("review/<int:review_id>/update/", views.update_review, name="update_review"),
    path("review/<int:review_id>/delete/", views.delete_review, name="delete_review"),

]

src/tickets/urls.py
from django.urls import path
from . import views

app_name = "ticket"
urlpatterns = [
    path("create-ticket", views.create_ticket, name="create_ticket"),
    path("edit-ticket/<int:id_ticket>/", views.edit_ticket, name="edit_ticket"),
    path("delete-ticket/<int:id_ticket>/", views.delete_ticket, name="delete_ticket"),
]

src/feed/models.py
from django.db import models

# Create your models here.

src/feed/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render
from tickets.models import Ticket
from review.models import Review


@login_required
def home_page(request):
    context = {}
    ticket = Ticket.objects.filter(
        Q(user=request.user) |
        Q(user__in=request.user.following.values_list("followed_user", flat=True))
    )
    review = Review.objects.filter(
        Q(user=request.user) |
        Q(user__in=request.user.following.values_list("followed_user", flat=True))
    )
    sorted_models_chain = sorted(chain(ticket, review), key=lambda instance: instance.time_created,
                                 reverse=True)
    context['feeds'] = sorted_models_chain
    ratings = [1, 2, 3, 4, 5]
    context['ratings'] = ratings
    return render(request, 'feed/home_page.html', context=context)

@login_required
def my_post(request):
    my_feed_review = Review.objects.filter(user=request.user)
    my_feed_ticket = Ticket.objects.filter(user=request.user)

    my_feed = sorted(chain(my_feed_review, my_feed_ticket), key=lambda instance: instance.time_created,
                     reverse=True)
    ratings = [1, 2, 3, 4, 5]

    context = {'feeds': my_feed,
               "ratings": ratings}
    return render(request, 'feed/posts_feed.html', context=context)

src/feed/templates/feed/home_page.html
{% extends 'base.html' %}

{% load models_tag %}

{% block title %}
    Feed
{% endblock title %}

{% block content %}
    <main class="main__container">
        <div class="feed__nav sub__btn">
            <a href="{% url 'ticket:create_ticket' %}">Demander une critique</a>
            <a href="{% url 'review:create-review' %}">Créer une critique</a>
        </div>
        <div class="feed">
            {% for feed in feeds %}
            {% if feed|model_type == "review" %}
                {% include 'feed/partials/review.html'%}
            {% elif feed|model_type == "ticket" %}
                {% include 'feed/partials/ticket.html'%}
            {% endif %}
            {% endfor%}
        </div>

    </main>

{% endblock content %}

src/feed/templates/feed/posts_feed.html
{% extends 'base.html' %}
{% load models_tag %}
{% block title %}
    Votre flux de post
{% endblock title%}

{% block content %}
    <main>
        <h2 class="title">Vos Posts</h2>
         <div class="feed">
            {% for feed in feeds %}
            {% if feed|model_type == "review" %}
                {% include 'feed/partials/review.html'%}
            {% elif feed|model_type == "ticket" %}
                {% include 'feed/partials/ticket.html'%}
            {% endif %}
            {% endfor%}
        </div>
    </main>
{% endblock content %}