src/authentication/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path
from authentication.views import LoginHomePageView, InscriptionView

app_name = "auth"
urlpatterns = [
    path("", LoginHomePageView.as_view(), name="home_page"),
    path("logout/", LogoutView.as_view(
        next_page=settings.LOGOUT_URL), name="logout"),
    path("inscription/", InscriptionView.as_view(), name="inscription"),
]

src/flux/urls.py
from django.urls import path
from flux.views import FluxView, DisplayMyPost


app_name = 'flux'
urlpatterns = [
    path("", FluxView.as_view(), name="flux_view"),
    path("posts/", DisplayMyPost.as_view(), name="my_posts"),
]

src/litrevue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("home/", include("flux.urls")),
    path("home/reviews/", include("reviews.urls")),
    path("home/follow/", include("subscriber.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/subscriber/urls.py
from django.urls import path
from subscriber.views import follow_page, UnfollowUserView


app_name = "follow"
urlpatterns = [
    path("", follow_page, name="follow"),
    path('unfollow/<int:user_id>/', UnfollowUserView.as_view(), name='unfollow_user'),

]

src/litrevue/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home Page{% endblock title %}</title>
</head>
<body>
    <nav>
        <h1>LITReview</h1>
        {% if user.is_authenticated %}
            <a href="{% url 'flux:flux_view' %}">Flux</a>
            <a href="{% url 'flux:my_posts' %}">Posts</a>
            <a href="{% url 'follow:follow' %}">Abonnements</a>
            <form method="post" action="{% url 'auth:logout' %}">
                {% csrf_token %}
                <button type="submit">Se déconnecter</button>
            </form>
        {% endif %}
    </nav>
    {% block content %}

    {% endblock content %}
</body>
</html>