src/authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path("login/", views.login_page, name="login_page"),
    path("logout/", views.logout_page, name="logout_page"),
    path("register/", views.create_account, name="register_page"),
    path("follow/", views.follow_page, name="follow"),
    path("unfollow/<int:user_to_unfollow>/", views.unfollow_user, name="unfollow_user"),
]

src/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("feed", views.my_post, name="my_feed"),
]

src/litrevue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("feed/", include("feed.urls")),
    path("tickets/", include("tickets.urls")),
    path("reviews/", include("review.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>
<body>
    {% if messages %}
		<div class="messages">
		{% for message in messages %}
            {{ message }}
		{% endfor %}
		</div>
	{% endif %}
    {% include 'nav-bar.html' %}
    {% block content %} {% endblock content %}
</body>
</html>

src/templates/nav-bar.html
<nav class="main-nav">
    <header class="main-logo">
            <h2 class="logo">LITReview</h2>
    </header>
    <div class="nav-bar">
        <ul class="items">
            {% if request.user.is_authenticated %}
            <li class="item"><a href="{% url 'feed:home'%}">Flux</a></li>
            <li class="item"><a href="{% url 'feed:my_feed'%}">Posts</a></li>
            <li class="item"><a href="{% url 'auth:follow' %}">Abonnements</a></li>
            <li class="item"><a href="{% url 'auth:logout_page' %}">Se déconnecter</a></li>
            {% endif %}
        </ul>
    </div>
</nav>