src/flux/urls.py
from django.urls import path
from flux.views import FluxView, DisplayMyPost


app_name = 'flux'
urlpatterns = [
    path("", FluxView.as_view(), name="flux_view"),
    path("posts/", DisplayMyPost.as_view(), name="my_posts"),
]

src/litrevue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("home/", include("flux.urls")),
    path("home/reviews/", include("reviews.urls")),
    path("home/follow/", include("subscriber.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reviews/urls.py
from django.urls import path
from reviews.views import CreateTicketView, CreateReviewView, review_about_ticket, modify_ticket, delete_ticket, modify_review


app_name = "review"
urlpatterns = [
    path("create-ticket/", CreateTicketView.as_view(), name="create_ticket"),
    path("create-review", CreateReviewView.as_view(), name="create_review"),
    path("review/<int:ticket_id>", review_about_ticket, name="review_ticket"),
    path("ticket/<int:ticket_id>", modify_ticket, name="update_ticket"),
    path("ticket/delete/d<int:ticket_id>", delete_ticket, name="delete_ticket"),
    path("review/<int:review_id>/update/", modify_review, name="modify_review"),

]

src/flux/models.py
from django.db import models

# Create your models here.

src/flux/views.py
from itertools import chain

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, CharField, Value
from django.shortcuts import render
from django.views.generic import TemplateView
from reviews.models import Ticket, Review


class FluxView(LoginRequiredMixin, TemplateView):
    template_name = 'flux/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tickets = Ticket.objects.filter(
            Q(user=self.request.user) |
            Q(user__in=self.request.user.follows.all())
        ).annotate(content_type=Value('TICKET', CharField()))

        reviews = Review.objects.filter(
            Q(user=self.request.user) |
            Q(user__in=self.request.user.follows.all()) |
            Q(ticket__user=self.request.user)
        ).annotate(content_type=Value('REVIEW', CharField()))

        context["rating_range"] = list(range(1,6))
        for ticket in tickets:
            ticket.has_user_reviewed = reviews.filter(ticket=ticket, user=self.request.user).exists()
        for review in reviews:
            review.has_user_reviewed = reviews.filter(ticket=review.ticket, user=self.request.user).exists()
        context["all_flux"] = sorted(chain(tickets, reviews),
                                     key=lambda instance: instance.time_created, reverse=True)
        return context


class DisplayMyPost(LoginRequiredMixin, TemplateView):
    template_name = 'flux/posts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tickets"] = Ticket.objects.filter(user=self.request.user)
        context["reviews"] = Review.objects.filter(user=self.request.user)
        context["rating_range"] = list(range(1,6))
        context["all_flux"] = sorted(chain(context["tickets"], context["reviews"]),
                                     key=lambda instance: instance.time_created, reverse=True)
        return context

src/flux/templates/flux/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <h1>{{user.username}}</h1>
    <div>
        <a href="{% url 'review:create_ticket' %}">Demander une critique</a>
        <a href="{% url 'review:create_review' %}">Céer une critique</a>
    </div>

    <div>
        {% for instance in all_flux %}
            {% if instance.content_type == "TICKET" %}
                {% include 'flux/partials/ticket_snippet.html' %}
            {% elif instance.content_type == "REVIEW" %}
                {% include 'flux/partials/review_snippet.html' %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

src/flux/templates/flux/posts.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}
    My Posts
{% endblock title %}

{% block content %}
    <h2>Vos posts</h2>
    <div>
     {% for instance in all_flux %}
            {% if instance|get_instance_name == "ticket" %}
                <p>{% posted_by_display instance.user %} demandé une critique</p>
                <p>{{instance.time_created}}</p>
                <p>{{instance.title}}</p>
                <p>{{instance.description}}</p>
                {% if instance.image %}
                    <img src="{{instance.image.url}}" alt="{{instance.title}}">
                {% endif %}
                <a href="{% url 'review:update_ticket' instance.id %}">Modifier</a>
                <a href="{% url 'review:delete_ticket' instance.id %}">Supprimer</a>
            {% elif instance|get_instance_name == "review" %}

                <p>{% posted_by_display instance.user%} publié une critique</p>
                <p>{{instance.time_created}}</p>
                <p>{{instance.headline}} - </p>
                 {% for i in rating_range %}
                    {% if i <= instance.rating %}
                        ★
                    {% else %}
                        ☆
                    {% endif %}
                {% endfor %}
                <p>{{instance.body}}</p>
                <p>TICKET TODO CSS</p>
                <p>ticket - {{instance.ticket.user.username}}</p>
                <p>{{instance.ticket.title}}</p>
                {% if instance.ticket.image %}
                    <img src="{{instance.ticket.image.url}}" alt="{{instance.ticket.title}}">
                {% endif %}
                <a href="{% url 'review:modify_review' instance.id%}">Modifier</a>
                <a href="">Supprimer</a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}