src/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("feed", views.my_post, name="my_feed"),
]

src/litrevue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("feed/", include("feed.urls")),
    path("tickets/", include("tickets.urls")),
    path("reviews/", include("review.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/review/urls.py
from django.urls import path

from . import views

app_name = "review"
urlpatterns = [
    path("create-review/", views.create_review, name="create-review"),
    path("review/<int:ticket_id>/", views.respond_to_ticket, name="review"),
    path("review/<int:review_id>/update/", views.update_review, name="update_review"),
    path("review/<int:review_id>/delete/", views.delete_review, name="delete_review"),

]

src/tickets/urls.py
from django.urls import path
from . import views

app_name = "ticket"
urlpatterns = [
    path("create-ticket", views.create_ticket, name="create_ticket"),
    path("edit-ticket/<int:id_ticket>/", views.edit_ticket, name="edit_ticket"),
    path("delete-ticket/<int:id_ticket>/", views.delete_ticket, name="delete_ticket"),
]

src/feed/models.py
from django.db import models

# Create your models here.

src/tickets/models.py
from PIL import Image
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def resize_photo(self):
        if self.image:
            img_path = self.image.path
            img = Image.open(img_path)
            img = img.resize((200, 300))
            img.save(img_path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_photo()

    class Meta:
        ordering = ['-time_created']
        verbose_name = 'Ticket'

src/tickets/forms.py
from django import forms

from . import models


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ["title", "description", "image"]

src/feed/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render
from tickets.models import Ticket
from review.models import Review


@login_required
def home_page(request):
    context = {}
    ticket = Ticket.objects.filter(
        Q(user=request.user) |
        Q(user__in=request.user.following.values_list("followed_user", flat=True))
    )
    review = Review.objects.filter(
        Q(user=request.user) |
        Q(user__in=request.user.following.values_list("followed_user", flat=True))
    )
    sorted_models_chain = sorted(chain(ticket, review), key=lambda instance: instance.time_created,
                                 reverse=True)
    context['feeds'] = sorted_models_chain
    ratings = [1, 2, 3, 4, 5]
    context['ratings'] = ratings
    return render(request, 'feed/home_page.html', context=context)

@login_required
def my_post(request):
    my_feed_review = Review.objects.filter(user=request.user)
    my_feed_ticket = Ticket.objects.filter(user=request.user)

    my_feed = sorted(chain(my_feed_review, my_feed_ticket), key=lambda instance: instance.time_created,
                     reverse=True)
    ratings = [1, 2, 3, 4, 5]

    context = {'feeds': my_feed,
               "ratings": ratings}
    return render(request, 'feed/posts_feed.html', context=context)

src/tickets/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from . import forms
from .models import Ticket


@login_required
def create_ticket(request):
    ticket_form = forms.TicketForm()
    if request.method == "POST":
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
        return redirect("feed:home")

    return render(request, 'tickets/ticket_form.html', {"ticket_form": ticket_form})


@login_required
def edit_ticket(request, id_ticket):
    try:
        ticket = Ticket.objects.get(id=id_ticket, user=request.user)
    except:
        return redirect("feed:home")
    else:
        ticket_form = forms.TicketForm(instance=ticket)

        if request.method == "POST":
            ticket_form = forms.TicketForm(request.POST, request.FILES, instance=ticket)
            if ticket_form.is_valid():
                ticket_form.save()
                return redirect("feed:home")
    return render(request, 'tickets/ticket_form.html', {"ticket_form": ticket_form})


@login_required
def delete_ticket(request, id_ticket):
    try:
        ticket = Ticket.objects.get(id=id_ticket, user=request.user)
    except:
        return redirect("feed:home")
    else:
        if request.method == "POST":
            ticket.delete()
            return redirect("feed:home")
    return render(request, 'tickets/delete_ticket.html', {"feed": ticket})

src/feed/templates/feed/partials/review.html
{% load models_tag %}
<div class="review box">
                    <small>{% post_by feed.user %} publié une critique - {{feed.time_created}}</small>
                    <h2>{{feed.headline}}</h2>
                    <div>
                        {% for i in ratings %}
                            {% if i <= feed.rating %}
                                        ★
                            {% else %}
                                        ☆
                            {% endif %}
                        {% endfor%}
                    </div>
                    <p>{{feed.body}}</p>
                    <div class="ticket ticK-review">
                        <small>Ticket par {% post_by feed.user %}</small>
                        <h3>{{feed.ticket.title}}</h3>
                        <p>{{feed.ticket.description}}</p>
                        {% if feed.ticket.image %}
                            <img src="{{feed.ticket.image.url}}">
                        {% endif %}
                    </div>
                     {% if feed.user == request.user and request.resolver_match.view_name == "feed:my_feed" %}
                        <div class="btn__submit option_btn">
                            <a href="{% url 'review:update_review' feed.id%}">Modifier</a>
                            <a href="{% url 'review:delete_review' feed.id%}">Supprimer</a>
                        </div>
                    {% endif %}
            </div>

src/feed/templates/feed/partials/ticket.html
{% load models_tag %}
{% can_create_review feed.id as can_review %}

<div class="ticket box">
                    <small>{% post_by feed.user %} demandé une critique - {{feed.time_created}}</small>
                    <h2>{{feed.title}}</h2>
                    <p>{{feed.description}}</p>
                    {% if feed.image %}
                            <img src="{{feed.image.url}}">
                    {% endif %}

                    {% if can_review  %}
                    <div class=btn__critique>
                        <a href="{% url 'review:review' feed.id %}">Créer une critique</a>

                    </div>
                    {% endif %}
                    {% if feed.user == request.user and request.resolver_match.view_name == "feed:my_feed" %}
                        <div class="btn__submit option_btn">
                            <a href="{% url 'ticket:edit_ticket' feed.id%}">Modifier</a>
                            <a href="{% url 'ticket:delete_ticket' feed.id%}">Supprimer</a>
                        </div>
                    {% endif %}
                </div>