src/authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path("login/", views.login_page, name="login_page"),
    path("logout/", views.logout_page, name="logout_page"),
    path("register/", views.create_account, name="register_page"),
    path("follow/", views.follow_page, name="follow"),
    path("unfollow/<int:user_to_unfollow>/", views.unfollow_user, name="unfollow_user"),
]

src/feed/urls.py
from django.urls import path

from . import views

app_name = "feed"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("feed", views.my_post, name="my_feed"),
]

src/litrevue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("feed/", include("feed.urls")),
    path("tickets/", include("tickets.urls")),
    path("reviews/", include("review.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserCustom(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(blank=True, null=True)


class UserFollows(models.Model):
    user = models.ForeignKey(UserCustom, on_delete=models.CASCADE, related_name="following")
    followed_user = models.ForeignKey(UserCustom, on_delete=models.CASCADE, related_name="followed_by")

    class Meta:
        unique_together = ("user", "followed_user")

    def is_following(self, user):
        return UserFollows.objects.filter(user=self, followed_user=user).exists()

src/authentication/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

src/authentication/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from . import models
from . import forms


def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        try:
            user = models.UserCustom.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('feed:home')
        else:
            messages.error(request, 'Username OR password does not exit')
    return render(request, 'authentication/login_page.html')


@login_required
def logout_page(request):
    logout(request)
    return redirect(settings.LOGIN_URL)


@login_required
def follow_page(request):
    user_to_follow = models.UserCustom.objects.all().exclude(id=request.user.id)
    if request.method == "POST":
        user_search = request.POST.get("follow_user")
        if user_search == request.user.username:
            messages.error(request, 'You cannot follow yourself')
        else:
            try:
                following_user = models.UserCustom.objects.get(username=user_search)

                if models.UserFollows.objects.filter(user=request.user, followed_user=following_user).exists():
                    messages.error(request, "Vous suivez déjà cet utilisateur.")
                else:
                    models.UserFollows.objects.create(user=request.user, followed_user=following_user)
                    messages.success(request, f"Vous suivez maintenant {following_user.username}.")

            except models.UserCustom.DoesNotExist:
                messages.error(request, "Utilisateur inconnu.")

    following_user = models.UserCustom.objects.filter(followed_by__user=request.user)
    followers = models.UserCustom.objects.filter(following__followed_user=request.user)
    print(followers)
    return render(request, 'authentication/follow_page.html', {'user_to_follow': user_to_follow,
                                                               'following_user': following_user,
                                                               'following_me': followers})


@login_required
def unfollow_user(request, user_to_unfollow):
    user_to_unfollow = get_object_or_404(models.UserCustom, id=user_to_unfollow)
    follow_relation = models.UserFollows.objects.filter(user=request.user, followed_user=user_to_unfollow).first()

    if follow_relation:
        follow_relation.delete()
        messages.success(request, f"Vous avez arrêté de suivre {user_to_unfollow.username}.")
    else:
        messages.error(request, "Vous ne suivez pas cet utilisateur.")

    return redirect("auth:follow")


def create_account(request):
    forms_page = forms.CreateUserForm()
    if request.method == "POST":
        forms_page = forms.CreateUserForm(request.POST)
        if forms_page.is_valid():
            user = forms_page.save()
            print(user)
            login(request, user)
            return redirect('feed:home')
    return render(request, 'authentication/register.html', {'forms_page': forms_page})

src/authentication/templates/authentication/follow_page.html
{% extends 'base.html' %}

{% block title %}
    follows
{% endblock title %}

{% block content %}
    <div class="main__container">
    <div >
    <h2>Suivre d'autres utilisateurs</h2>
    <form method="POST">
        {% csrf_token %}
        <input required type="text" name="follow_user" list="user-list" placeholder="Nom d'utilisateur" />
        <datalist id="user-list">
            {% for user in user_to_follow %}
                <option value="{{ user.username }}">{{ user.username }}</option>
            {% endfor %}
        </datalist>
        <input type="submit" value="Follow">
    </form>
        </div>
    <div class="container">
        <h2>Abonnements</h2>
        {% for follow in following_user %}
            <div class="folloging__class">
                <h3>{{follow.username}}</h3>
                <form method="post" action="{% url 'auth:unfollow_user' follow.pk %}">
                    {% csrf_token %}
                    <input name="unfollow" type="submit" value="Désabonner">
                </form>
            </div>
        {% endfor %}
        <div>
            <h2>Abonnés</h2>
            {% for following in following_me%}
                <h3>{{following.username}}</h3>
            {% endfor %}
        </div>
    </div>
        </div>
{% endblock content %}

src/authentication/templates/authentication/login_page.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock title %}

{% block content %}
    <main class="main">
        <section>
            <h2>Inscrivez-vous maintenant</h2>
            <div class="sub__btn">
                <a href="{% url 'auth:register_page' %}">S'inscrire</a>
            </div>
        </section>

        <section>
            <h2>Connectez-vous</h2>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form_login">
                        <input type="text" placeholder="Nom d'utilisateur" name="username">
                        <input type="password" placeholder="Mot de passe" name="password">
                    </div>
                    <div  class="btn__submit">
                        <input type="submit" value="Se connecter">
                    </div>

                </form>
            </div>
        </section>
    </main>
{% endblock content %}

src/authentication/templates/authentication/register.html
{% extends 'base.html' %}

{% block title %}
    register
{% endblock title %}

{% block content %}
    <div>
        <h2 class="title">Inscrivez-vous</h2>
        <form method="post">
            {% csrf_token %}
            {{forms_page.as_p}}
            <div>
                <a href="{% url 'auth:login_page' %}">retourner</a>
                <input type="submit" value="s'inscrire">
            </div>

        </form>
    </div>
{% endblock content %}