src/authentication/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path
from authentication.views import LoginHomePageView, InscriptionView

app_name = "auth"
urlpatterns = [
    path("", LoginHomePageView.as_view(), name="home_page"),
    path("logout/", LogoutView.as_view(
        next_page=settings.LOGOUT_URL), name="logout"),
    path("inscription/", InscriptionView.as_view(), name="inscription"),
]

src/flux/urls.py
from django.urls import path
from flux.views import FluxView, DisplayMyPost


app_name = 'flux'
urlpatterns = [
    path("", FluxView.as_view(), name="flux_view"),
    path("posts/", DisplayMyPost.as_view(), name="my_posts"),
]

src/litrevue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("home/", include("flux.urls")),
    path("home/reviews/", include("reviews.urls")),
    path("home/follow/", include("subscriber.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
        Custom user model who have same attributes from AbstractUser
        Whe give him a role :
            - CREATOR
            - SUBSCRIBER
        A Creator have the power of delete a ticket or a review ticket
    """
    CREATOR = "CREATOR"
    SUBSCRIBER = "SUBSCRIBER"
    USER_ROLE = (
        (CREATOR, "Creator"),
        (SUBSCRIBER, "Subscriber"),
    )

    role = models.CharField(max_length=30, choices=USER_ROLE, default=SUBSCRIBER, verbose_name="User_role")
    follows = models.ManyToManyField(
        'self', through='subscriber.UserFollows', related_name='is_followed_by', symmetrical=False
    )

src/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class InscriptionForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

src/authentication/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from authentication.forms import LoginForm, InscriptionForm
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView


# Create your views here.
class LoginHomePageView(LoginView):
    template_name = "authentication/home_page.html"
    form_class = LoginForm
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'You have successfully logged in.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Nom d'utilisateur ou mot de passe incorrect.")
        return super().form_invalid(form)


class InscriptionView(FormView):
    template_name = "authentication/inscription.html"
    form_class = InscriptionForm
    success_url = reverse_lazy("flux:flux_view")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

src/authentication/templates/authentication/home_page.html
{% extends 'base.html' %}

{% block title %}
  Page d'accueil
{% endblock title %}

{% block content %}
    {% if not user.is_authenticated %}
    <h2>Inscrivez-vous maintenant</h2>
    <a href="{% url 'auth:inscription' %}">S'inscrire</a>

    <h2>Connectez-vous</h2>
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Se connecter</button>
    </form>
    {% else %}
        <h1>Vous êtes connecter en tant que {{user.username}}</h1>
    {% endif %}
{% endblock content %}

src/authentication/templates/authentication/inscription.html
{% extends 'base.html' %}

{% block title %}
  Inscription
{% endblock title %}


{% block content %}
  <h1>Inscrivez-vous</h1>
  <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">S'inscrire</button>
    <a href="{% url 'auth:home_page' %}">Retourner</a>
  </form>
{% endblock content %}